apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: janus
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: janus-argo
    server: 'https://kubernetes.default.svc'
  source:
    path: janus-chart/charts/backstage/
    repoURL: 'https://github.com/kadel/janus-argo'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true

